services:
# 🦉 Apache Zookeeper (Necesario para Kafka)
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  # 🔥 Apache Kafka
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  # 🚀 Backend (Node.js + Express)
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # Monta el código fuente en desarrollo
      - /app/node_modules  # Evita sobrescribir node_modules
    environment:
      - NODE_ENV=development
      - KAFKA_BROKER=kafka:9092  # Agregamos Kafka a las variables de entorno
    command: npm run dev  # Usa nodemon para desarrollo
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure

  # 🌍 Frontend (Angular)
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://backend:3000
    volumes:
      - ./frontend:/app  # Monta el código fuente en desarrollo
      - /app/node_modules  # Evita sobreescribir dependencias
    command: ng serve --host 0.0.0.0 --disable-host-check
    restart: on-failure

  # 🛢️ Base de datos PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: voting_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d voting_system"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 🛢️ Base de datos MongoDB
  mongodb:
    image: mongo:6
    environment:
      - MONGO_URI=mongodb://mongodb:27017/voting_system
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: on-failure
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 3

# 🛑 Volúmenes para bases de datos
volumes:
  postgres_data:
    name: voting_postgres_data
  mongo_data:
    name: voting_mongo_data
